name: causality-exploration
channels:
  - defaults
dependencies:
  - python=3.9.18
  - numpy=1.20.*
  - pip=23.3.1
  - pip:
    - matplotlib==3.9.1
    - seaborn==0.13.2
    - torch==2.3.1
    - transformers==4.43.1